
import 'bootstrap/dist/css/bootstrap.min.css';
import StoreProvider from "@/lib/StoreProvider";
import React from "react";
import Head from 'next/head';



export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({children,}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body>
        <StoreProvider>
            {children}
        </StoreProvider>
        </body>
        </html>
    )
}
